<a href="https://colab.research.google.com/github/AbhinavKumar07/C125/blob/main/C125.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [63]:
import numpy as np
import random

rewards = np.array([
    [-1,-1,-1,-1,0,-1],
    [-1,-1,-1,0,-1,100],
    [-1,-1,-1,0,-1,-1],
    [-1,0,0,-1,-1,-1],
    [0,-1,-1,-1,-1,100],
    [-1,-1,-1,-1,0,100]
])



In [64]:
def set_initial_state():
  return np.random.randint(0,6)

set_initial_state()

0

In [65]:
def get_action(current_state , reward_matrix):
  available_action = []
  print("Reward_matrix","\n" , reward_matrix)

  for action in enumerate(reward_matrix[current_state]):
    if action[1] != -1 :
      available_action.append(action[0])

  choose_action = random.choice(available_action)
  print("Random choice of action from" , available_action , "is" , choose_action)
  return choose_action

In [66]:
#current_state = 4
#action = get_action(current_state , rewards)
#print(action)

In [67]:
current_state = 5
action = get_action(current_state , rewards)
print(action)

Reward_matrix 
 [[ -1  -1  -1  -1   0  -1]
 [ -1  -1  -1   0  -1 100]
 [ -1  -1  -1   0  -1  -1]
 [ -1   0   0  -1  -1  -1]
 [  0  -1  -1  -1  -1 100]
 [ -1  -1  -1  -1   0 100]]
Random choice of action from [4, 5] is 4
4


In [68]:
#current_state = 0
#action = get_action(current_state , rewards)
#print(action)

In [69]:
#current_state = 1
#action = get_action(current_state , rewards)
#print(action)

C125


In [70]:
q_matrix = np.zeros([6,6])
print(q_matrix)


[[0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]]


In [71]:
gamma = 0.8
def take_action(current_state,reward_matrix,gamma):
  action = get_action(current_state,reward_matrix)
  current_reward = reward_matrix[current_state,action]
  print("Current reward:" , current_reward)

  q_value = max(q_matrix[action])
  print("q-value:" , q_value)

  q_current_state = current_reward + (gamma * q_value)
  print("Q-current-state",q_current_state)

  q_matrix[current_state,action] = q_current_state
  print("Q-matrix:" ,"\n" , q_matrix)

  new_state = action

take_action(current_state,rewards,gamma)

Reward_matrix 
 [[ -1  -1  -1  -1   0  -1]
 [ -1  -1  -1   0  -1 100]
 [ -1  -1  -1   0  -1  -1]
 [ -1   0   0  -1  -1  -1]
 [  0  -1  -1  -1  -1 100]
 [ -1  -1  -1  -1   0 100]]
Random choice of action from [4, 5] is 5
Current reward: 100
q-value: 0.0
Q-current-state 100.0
Q-matrix: 
 [[  0.   0.   0.   0.   0.   0.]
 [  0.   0.   0.   0.   0.   0.]
 [  0.   0.   0.   0.   0.   0.]
 [  0.   0.   0.   0.   0.   0.]
 [  0.   0.   0.   0.   0.   0.]
 [  0.   0.   0.   0.   0. 100.]]
